//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public System.Guid UserAccountId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string LoginAttempts { get; set; }
        public string Locked { get; set; }
        public string IsAdmin { get; set; }
        public string ConfirmedEmail { get; set; }
        public string IsAuthorized { get; set; }
        public string LastLogin { get; set; }
        public string SignupDate { get; set; }
        public System.Guid UserUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
